CXX ?= g++
PROG = posttoken
COURSE_TEST_ROOT = $(wildcard course/pa2)
DEV_BUILD_LOCK = ../obj/.dev-build.lock

.PHONY: all test ref-test dev-shared-target

all: ../dev/$(PROG)

ifeq ($(COURSE_TEST_ROOT),)
test: dev-shared-target
	scripts/run_all_tests.pl ../dev/$(PROG) my tests
	scripts/compare_results.pl ref my tests
else
test: dev-shared-target
	scripts/run_all_tests.pl ../dev/$(PROG) my tests
	scripts/compare_results.pl ref my tests
	scripts/run_all_tests.pl ../dev/$(PROG) my $(COURSE_TEST_ROOT)
	scripts/compare_results.pl ref my $(COURSE_TEST_ROOT)
endif

../dev/$(PROG):
	@mkdir -p ../obj
	@lockdir=$(DEV_BUILD_LOCK); \
	while ! mkdir $$lockdir 2>/dev/null; do sleep 1; done; \
	trap 'rmdir "$$lockdir"' EXIT HUP INT TERM; \
	$(MAKE) -C ../dev $(PROG)

dev-shared-target:
	@if [ "$(CPGM_SKIP_DEV_REBUILD)" = "1" ]; then \
		true; \
	else \
		$(MAKE) --no-print-directory ../dev/$(PROG); \
	fi

ref-test:
	scripts/run_all_tests.pl posttoken-ref ref tests
